language: cpp

compiler:
- gcc
- clang

sudo: required

dist: trusty

install:
  - sudo apt-get install libboost-dev

script: make test

env:
- CXXFLAGS=-std=c++98
- CXXFLAGS=-std=c++03
- CXXFLAGS=-std=c++11
- CXXFLAGS=-std=c++14
- CXXFLAGS=-std=c++17

matrix:
  exclude: # travis service doesn't have new enough gcc and clang for these tests.
  - compiler: gcc
    env: CXXFLAGS=-std=c++14
  - compiler: gcc
    env: CXXFLAGS=-std=c++17
  - compiler: clang
    env: CXXFLAGS=-std=c++14
  - compiler: clang
    env: CXXFLAGS=-std=c++17
